### ISSUE TITLE
Training model for the purpose of reproducibility

### ISSUE THREAD

**Issue by AravindRK99** [shizuo-kaji/CTKernelConversion#1]
Thank you so much for this wonderful work. I would like to know how I can train these models released for my own data? I have a different set of reconstruction kernels from a different vendor and I would like to understand the procedure to train your model on my data. 

Thank you. 
Aravind

**Comment by shizuo-kaji** [comment]
Hello.
Models can be trained by another set of codes: 
https://github.com/shizuo-kaji/PairedImageTranslation
However, due to the discontinuation of Chainer, they are not maintained or very convenient. Sorry.

**Comment by AravindRK99** [comment]
Thank you for your response! Does that mean that I will not be able to implement the code ?

**Comment by shizuo-kaji** [comment]
It is currently not easy to set up Chainer with GPU. 
If you have a working environment with Chainer, you can use
https://github.com/shizuo-kaji/PairedImageTranslation
for the kernel conversion with your own dataset.

**Comment by AravindRK99** [comment]
Thank you so much for the response!
